### ISSUE TITLE
using MyPal68 Portable with XP AND Win10 does not work

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal68#105]
When I try to open MyPal Portable in Win 10, after XP, the profile does not load.
The problem is "addonStartup.json.lz4"
I must delete this file, then it works.

please check. Thanx :-)

**Comment by Feodor2** [comment]
I can nothing to do with win10 because i and everyone else around do not use it. I did this with win8 and no error was.

**Comment by sirrooster** [comment]
I need win10 to transfer my tax-bill to the goverment. The goverment software does not support XP :-(
And I need it for google sites which have some other security restriction. Maybe OAuth2 or things like that. I don't know.
Eg this google help community site does not full open in MyPal68. 
https://support.google.com/accounts/thread/168513255
It does not show the posting (forum-thread) and has not full functionallity.

What is this "addonStartup.json.lz4" good for???
When I delete it, all works proper in win10.
After starting MyPal68 with deleted "addonStartup.json.lz4" the file is replaced and then it's no problem to start MyPal again.
Can you fully eleminate it?

**Comment by Feodor2** [comment]
So why do you use mypal? you can easely take and use firefox 91 and even greater
But addonStartup.json.lz4 makes another error for portable when you move it, i noticed and shall fix later.

**Comment by sirrooster** [comment]
re: "So why do you use mypal? you can easely take and use firefox 91 and even greater"
Because I think that FireFox91 would crash my MyPal68 pofile. Isn't it?
And I don't want create a new profile for FireFox91.

re: "But addonStartup.json.lz4 makes another error for portable when you move it"
So I hope this fix will tix the win10 issue, too.

**Comment by Neotmiren** [comment]
re: "I can nothing to do with win10 because i and everyone else around do not use it"

Под XP или Server 2003 надо скачать с nnmclub.to DVD 2k10_Live 7.40 (по ряду причин можно предпочесть более старую версию 7.25, если отыскать её торрент).

С образа DVD можно грузиться под VirtualBox 5.24 (по опыту, наилучшая версия для NT 5.x). Подключить к виртуальной машине DVD 2k10 и стандартный VirtualBox'овый CD-образ с драйверами, куда дописывается свой .cmd файл, запускающий сперва установку драйверов VirtualBox (с ключами, чтобы обойтись без интерактивных запросов). Затем надо запустить службу sc start VBoxSF, чтобы обойтись без перезагрузки ОС. Затем подсоединить диски основной системы командами вида net use C: \\vboxsvr\C_DRIVE и выполнить любые свои автонастройки. Никакие образы HDD создавать и подключать не надо. Грузится всё быстро и удобно, если хватает умений по части составления .cmd файлов.

Таким образом получаем возможность проверять работу программ в WinPE 2003 32-bit, 7 32/64, 8 32/64, 10 32/64. Кроме того, доступ к любым новейшим обозревателям из-под этих систем, если в системе доступно памяти от хотя бы 6 ГБ и выше - их видит 2003 или XP с т.н. "PAE патчем".

Ваша версия FF 68, как и все прочие обозреватели, работает под всеми перечисленными ОС с DVD 2k10.
