### ISSUE TITLE
GMX can't open

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#17]
The website https://www.gmx.net/ can't open.
After a short time comes an error message.

**Comment by NoNameNeeded2** [comment]
I can confirm this.
Even with a newer useragent it doesn't work correctly.
It does however work with Firefox68 so this is a Mypal68 specific problem.

**Comment by win98se** [comment]
Workaround: In `about:config`, create a new preference named `general.useragent.override.gmx.net`, set it as `Mozilla/5.0 (Windows NT 5.1; rv:68.0) Gecko/20100101 Firefox/68.0` (or whatever user agent that doesn't include the word `Mypal`), done.

BTW, per-site user agent override options are removed since Firefox 71, so if Feodor2 will work on Firefox 78/91 in (near I hope :p) future, he will have to try reverting [this change](https://bugzilla.mozilla.org/show_bug.cgi?id=1513574). ([Related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1589607))
