### ISSUE TITLE
For those who cannot wait for an updated MyPal Browser...

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#196]
For those who cannot wait for an updated MyPal Browser, working with Windows XP, this one here works well, as I just found out:
Serpent v52.9.0 (2023-03-30) (32-bit)

**Comment by RamonUnch** [comment]
I would add the link to the main download page for Serpent:
http://rtfreesoft.blogspot.com/

Serpent is an unofficial fork of the Basilisk browser, based on the latest version of the UXP engine (PaleMoon). So you should not expect perfect web compatibility.

Also if you have issues related to Serpent (or other UXP browsers), you can go to [this thread on msfn.org](https://msfn.org/board/topic/184051-my-browser-builds-part-4/). If you cannot find an answer, you can try to ask on the thread, people are usually nice and will try to help.

As a quick reference with the recent builds you have the WebComponent that are now 99% functional and enabled by default, so you cab use GitHub (like with PaleMoon). If you want to go one step further you can set `dom.enable_performance_observer`;`true` to enable more web feature, it useful for GitHub if you want the auto-completion.

I use both MyPal68 and Serpent, I can say that on my system MyPal68 is much faster but it takes up more RAM so depending on the amount of RAM you have Serpent could actually be helpful.

Finally you might also be interested in [Palefill](https://martok.github.io/palefill/) that does some polyfill magic to improve further the web compatibility of UXP based browsers (including Serpent).

**Comment by IP-CAM** [comment]
Thanks for the Info on this. Speed is not my top Priority, it just has to fully work on the Sites I visit and use, and that's the Case now again.

**Comment by Feodor2** [comment]
I plan to do the update release before next month
You may want to check todays prerelease

**Comment by hue4** [comment]
We're very glad you're back!

**Comment by andika207** [comment]
@RamonUnch it's a shame that the person who took over the Basilisk difunct project will not backport it to XP.
if the Serpernt browser can work on XP I seriously believe the Basilisk could run equally well even though they are not based on the same platform. 
Serpent is likely based on the crap Palemoon 28 or so this is why it struggles despite having the multi process mode enabled by default.
there are so many good alternatives out there for W7 and up that nobody will be using the crap Basilisk without multi process

**Comment by andika207** [comment]
@RamonUnch I have not used the Serpent 52 for nearly a year now (where I still have more than 100 active open tabs LOL) the chrome 360 is so much faster but I miss things form the S52 because I like the FF layout much better
on the other hand, Mypal 68 is not a real option to me, coz it doesn't run faster than chrome 360 and it still crashes or pops many BSOD up
I love XP but I am aware that chrome 360 is not far from its EOL (maybe 2-3 more years ahead)

**Comment by RamonUnch** [comment]
I understand your concern @andika207 however I think there are some small misunderstanding here.
Roytam1 's NewMoon28 and Serpent are both based on the same UXP engine, same as the latest PaleMoon32 and Basilisk (even though it is named NewMoon28). If you use a one year old version then you should upgrade to the latest build, those last weeks very significant improvements were brought to the table in term of Web engine compatibility.
There are bugs and quirks of course that will differ because Basilisk and Serpent are not the same even if they should be functionally similar.

The Basilisk developer took the project in charge mostly for himself so he is not really willing to invest energy in XP support because he has no use for it, He is not against the Serpent project and is quite welcoming.

The real point of the PaleMoon and Basilisk projects is to have a true alternative to Chrome and Firefox, however it a few steps behind in term of web compatibility, This is why most Basilisk /PaleMoon users still need to have another web browser for sites that are not fully compatible. The web engine is improving, WebComponents were added a few weeks ago to Serpent this is Why I would recommend to update to the latest Serpent.

360 Chrome is quite good but there will be no more XP compatible builds in the future. Hopefully Both Basilisk and MyPal will advance fast enough to catch back the crazy modern web standard, for now they are both on a good trend. Thanks everyone involved.

**Comment by Logicomedian** [comment]
Thanks a lot. Your contribution & help to the still-standing WinXP user scene is legendary.

@Feodor2  Thank you.

@RamonUnch   Thank you.

How can we all, the simple users, show our support?

**Comment by andika207** [comment]
> The real point of the PaleMoon and Basilisk projects is to have a true alternative to Chrome and Firefox

@RamonUnch true sluggish alternative to be more exact. FF is already struggling to keep up against chrome speeds so just imagine this crap based on legacy web engines.

**Comment by andika207** [comment]
> The web engine is improving, WebComponents were added a few weeks ago to Serpent this is Why I would recommend to update to the latest Serpent

@RamonUnch I ocasionally use Basilisk on W7 and I feel really stressful when trying to open many tabs in a row because it freezes however on the original chrome I can have 100 tabs open at a time with no glitches as it's super smooth.
