### ISSUE TITLE
Problem with videos

### ISSUE THREAD

**Issue by NoNameNeeded2** [Feodor2/Mypal68#23]
Videos like this one don't seem to work

https://www.derstandard.at/story/2000134736665/putin-und-die-supermacht-china-hat-der-westen-immer-weniger?ref=rss

**Comment by Anbima** [comment]
I can not confirm.
Video is playing.

**Comment by NoNameNeeded2** [comment]
Did you install any additional plugins?

**Comment by win98se** [comment]
> Did you install any additional plugins?

@NoNameNeeded2 For me, yes - [AdGuard 3.6.17](https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/#:~:text=Download%20file-,Version%203.6.17,-Released%20Dec%2016) and [Return Youtube Dislike](https://addons.mozilla.org/en-US/firefox/addon/return-youtube-dislikes/). The latter should not affect the video though, because it's from Dailymotion.

**Comment by Anbima** [comment]
@NoNameNeeded2
Only uBlock Origin.
Try reload the page.

**Comment by NoNameNeeded2** [comment]
Doesn't work.

**Comment by Anbima** [comment]
The video is running.
![Screenshot](https://user-images.githubusercontent.com/49531928/163046554-efb2c302-c6aa-436c-b26a-71583f774aab.jpg)

**Comment by NoNameNeeded2** [comment]
NOW it works for me as well.
Even though it doesn't make a lot of sense.

All I did was that I used this new installer someone posted, I installed Mypal to a new folder (and a new profile) and suddenly BOTH installations show the video.
