### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by Batuhan445** [Feodor2/Mypal68#237]
here?

**Comment by unattendedplayer** [comment]
Thanks to Feodor2 (!), it's near impossible to do some languages (Because some language packs are DIFFERENT in structure). Thus will require you to check EVERY SINGLE LINE to make a proper working translation. My best bet would be learning English, definitely easier (or more enjoyable than checking every single line of hundreds of files).

**Comment by unattendedplayer** [comment]
You can prove me wrong by making the Turkish pack working on Mypal 68.13 though.

**Comment by Feodor2** [comment]
You are wrong @unattendedplayer
Nothing was changed since https://github.com/Feodor2/Mypal68/issues/203 
There are several new packs already done, anybody advanced user can do it.
So what wanted @Batuhan445, to do somebody langpack for him.
