### ISSUE TITLE
.exe installer

### ISSUE THREAD

**Issue by spinalgr1990** [Feodor2/Mypal68#315]
Where to find an .exe installer ??

**Comment by guilt** [comment]
This is not a bad idea. Release this once every year or something, the version of MyPal on the website with a working installer is so old. Now that you've gotten a great version of 68.13.7b, just make one update to the website with it. People will really benefit from it even though it means nothing to the development of this.

**Comment by NS-Clone** [comment]
why you ever need installer? o_O

**Comment by Feodor2** [comment]
I shall may provide installers when it will be stable
Yet it is not enough but closer

> all installers s@xxx

Regular user prefer installer for sure, also the reason not to provide it - mypal is not suitable for regular user, may be yet.

**Comment by guilt** [comment]
> why you ever need installer? o_O all installers s@xxx and it's invented by m$-zog to break installation on old machines (consumer society) :) all software must be portable not portable software invented by m$-zog and s@xxx
> 
> and also bcz m$-zog try to break portable software using we still use XP

That's why NSIS exists. Nullsoft made it open source way back and you could run those binaries happily in Win9x. They run happily on XP.

https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/index.html

**Comment by NS-Clone** [comment]
> Regular user prefer installer for sure, also the reason not to provide it - mypal is not suitable for regular user, may be yet.

regular users using win15

also all installers is suspicious
you never know where it start unpack/install it after start
and system restore can remove all you suspicious .exe installers...

**Comment by JimMP68User** [comment]
Method I have been using:

1. Download new Mypal version and put into Mypal browser directory such as: E:\Sw_dnld\Browser\Mypal
2. Example of latest would be: E:\Sw_dnld\Browser\Mypal\Mypal_68-13-7b
4. When download finishes, right click on "mypal-68.13.7.en-US.win32.zip" filename and select "Extract All"
5. Go into directory created named "mypal-68.13.7.en-US.win32" 
6. Click on "mypal" directory then on toolbar View | Details, click on column header "Type"
7. Look for exe file named "mypal.exe", right click and look for "Send to" and select "Desktop (create shortcut)" 
8. A link-icon will appear on the computer Desktop.

Now we will work to point Mypal to previous version Mypal directory holding files containing all bookmarks, site passwords and all (instead of "USERNAME" below you will see your Win Xp logon name)::

1. These will be in a directory here: C:\Documents and Settings\USERNAME\Application Data\Mypal68\Profiles\
2. Here is one example: C:\Documents and Settings\Jim\Application Data\Mypal68\Profiles\fmtxvubk.default-default-6
3. Hint: Look for most recently accessed directory by doing sort on "Date Modified" column (using View | Details)
4. Start Mypal (use shortcut created in step 8 above)
5. Click on Mypal "Open menu" icon button (upper right), then click "Help", then "Troubleshooting Information"
6. Under "Application Basics" section look for "Profiles" then click on "about:profiles"
7. Click on "Set as default profile" the one that has the name of the directory found in step 3 just above. This directory will be from your previous Mypal version.

More info: https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data

**Comment by rafm5** [comment]
But why, just to leave more junk on the hard drive? ¯\(ツ)/¯

**Comment by unattendedplayer** [comment]
I thought someone who uses XP in 2023 wouldn't mind extracting files manually...
