### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by unattendedplayer** [Feodor2/Mypal68#326]
In the original version of Firefox, we're able to get search suggestions as long as we have enabled it. But that's not the case with Mypal. If you type words in the search box (or address bar if you've disabled the search box), it won't return any suggestions (assuming you have keyword.enabled set to true).
Question: What caused it to break? Will it ever be fixed?

**Comment by Feodor2** [comment]
Enable this in options search section also depends on search provider

**Comment by zanud** [comment]
> I'm adding Google by its genuine webpage

This instruction is not suitable for modern version of Firefox (and MyPal).

> Shouldn't it bring the suggestions functionality as well?

Unfortunately, nowadays Google does not provide suggestions for OpenSearch plugins.

**Comment by zanud** [comment]
> Then why it works

Because server response to the request is a regular HTML file, which does not contain any special.

> and adds the search engine successfully (search bar must be enabled)?

Really?
![Google](https://github.com/Feodor2/Mypal68/assets/76625744/27050802-1676-4bc3-b49c-660adb430778)
Then where is a "green plus" sign for search engine adding?
(For comparison look at the search bar right now, when you are on the github.com.)

> Now, we must learn if there's a way to create an OpenSearch plugin with suggestions.

So called "OpenSearch plugin" is a simple text (well, XML) file, that contains a search engine name, URL for requests, and (optonally) URL for suggestions. By itself, it does nothing. Everything is done by a _[imaginable]_ "OpenSearch engine" browser, which sends requests to the given URLs.
Server responses to regular search queries are plain HTML files. Browser does not analise them, but displays to a user.
But server responses to queries for suggestions must be in a special format, and browser expects data only in this format and parses it.

So if server does not provide suggestions at all, or provides them not in the expected format but in some proprietary (like google.com does), then you can not overcome this by any OpenSearch plugin file.

So if you really need suggestions, use any search provider that suports suggestions as a default, but not Google.

**Comment by unattendedplayer** [comment]
> https://www.google.com/homepage/search/sp-firefox.html

You must visit here in order to add the engine. I'll blame feodor2 as he removed it in the first place. In original Firefox, Google is present and suggestions work without any problem. I hope Supermium will work on XP in the future so I can use it instead.
