### ISSUE TITLE
[Suggestion] Another version alongside this one - Should solve some of the issues

### ISSUE THREAD

**Issue by bfffggh** [Feodor2/Mypal68#328]
The version is 102.0esr, but it still needs to support WinXP. Can you try to make a 102.0esr version **alongside** this version?

You don't need to make that, failure is acceptable. Thanks.

**Comment by RamonUnch** [comment]
for now MyPal68.13.x is actually based on the Firefox78 JS engine. Feodor is working on updating the engine to the Firefox91 level, hopefully soon, then 102 will be the next step but There will be some time before that...
So the process is progressive in order to get everything working smoothly on XP.
have a look at #222
