### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#33]
@Feodor2
Is it enough if an update is copied to the old MyPal68 folder and existing files are overwritten, or should the directory and profiles be deleted before?

**Comment by NoNameNeeded2** [comment]
I certainly don't think your profile needs to be deleted when you update any browser.
This would be very cumbersome

**Comment by Anbima** [comment]
But it could be that also data is changed in the profiles.
about:config is also stored in the profiles, right?

**Comment by NoNameNeeded2** [comment]
Well, there are cases (like when you update from a very old version of Firefox (or Mypal) to a new one) where your old profile won't work very well with the new version of the browser.
In such a case it makes sense to create a new profile and copy everything you want to keep from your old profile to your new profile one by one, in order to learn which file or files of your old profile cause problems with your new version of Firefox (or Mypal). This way you could use as much as possible from your old profile without the files which cause problems.
But in general it's very likely that your old profile will work with an updated version of Mypal just as well as it did before the update.

**Comment by NoNameNeeded2** [comment]
I just updated to the new version (keeping my old profile) and it works just fine.

I did however delete everything that was in the program folder, just to make sure there are no files left from the old version (just in case the new version has one file less than the old version and the old file causes problems when it's still there)

**Comment by Feodor2** [comment]
Of course you may keep old profile, why do you think 68.12.1 is very old against 68.12.2.
Though i insist to make profile copies for update.
Like example rename mypal to to something mypal.old install new version to mypal  and copy profile there from mypal.old

**Comment by NoNameNeeded2** [comment]
No, of course version 68.12.1 isn't very old compared to 68.12.2 
What I wrote above was a more general answer.
Only if you have a very old version and update to a newer version, it might be necessary to use a new profile.

**Comment by Anbima** [comment]
@Feodor2
Since with myPal68 still many pages do not work, it may be good if you would continue with myPal91.
Or does it have a reason that you first do MyPal68?

**Comment by Anbima** [comment]
The cookie banners cause major problems on many German sites.
These are not displayed and then the page is not displayed.

**Comment by NEO-SPECTRUMAN** [comment]
> Or does it have a reason that you first do MyPal68?

maybe it still most comparable with XP

**Comment by NoNameNeeded2** [comment]
> 

Cookie banners?
Are there any cookie banners in Mypal68?

Maybe you use the addon "I don't care about cookies".
The older version does exactly what you described (cookie crap isn't shown and therefore the website won't work (correctly)).
But the new version of this addon fixes that.
It automatically agrees to the cookie crap and the website is shown as it should be.

**Comment by Anbima** [comment]
Please look here:
https://github.com/Feodor2/Mypal68/issues/16
