### ISSUE TITLE
68.13.7b not able to display pics in boxes and unable to use pulled down boxes for some sites

### ISSUE THREAD

**Issue by GPthermal** [Feodor2/Mypal68#352]
[mypal68 issues.docx](https://github.com/Feodor2/Mypal68/files/13855441/mypal68.issues.docx)
I have taking screen shot with the troubleshooting file info.

Thanks
Ken

**Comment by Feodor2** [comment]
Can anybody else confirm this? You seems confused with SSE version drop it and take previous one,

**Comment by zanud** [comment]
@GPthermal, @Feodor2 

Most probably images are not displayed because this site uses Javascript features which are not supported by MyPal68:

`SyntaxError: private fields are not currently supported`

**Comment by antisodomite** [comment]
Same problem here. Sites that were working perfectly under 68.13.3 now have this issue under 68.13.7. Two sites are ebay.com and albertsons.com for me. I tried to go back to 68.13.3 and it gives me an error message that my profile is not compatible with an older version. What can I do to get my profile from 68.13.8 to now work with older version 68.13.3?

**Comment by Feodor2** [comment]
That's because you do not look release notes, told not to take 8 verison - this is special edition, will get nothing but errors only.
What to do for return to previous version #320

**Comment by antisodomite** [comment]
Thanks for the reply. That file deletion worked. I actually did read the release notes. It sounded like for those that were on 68.13.7, there was no benefit to updating but that it would do no harm in doing so. I guess I read that wrong.

It looks like albertsons.com must have updated their site because certain thins don't load anymore. so it wasn't anything with the new release.

The browser is very stable except seems like it crashes a lot on youtube.com

Thanks for your diligence on this browser. I love it.
