### ISSUE TITLE
Mypal68 - Bluescreen about:memory

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#4]
When open about:memory, WinXP crashes in a bluescreen.

**Comment by Feodor2** [comment]
No Bluescreen at about:memory for me but when i hit "Minimize memory" my winxp has been totally crashed without blue screen.
So it is dangerous feature for now.

**Comment by Anbima** [comment]
Just a complete crash with bluescreen, when I close mypal.
![Screenshot](https://user-images.githubusercontent.com/49531928/162186112-bdb00f73-64a7-408e-a069-42da5b021cf7.jpg)

**Comment by pachuco** [comment]
> No Bluescreen at about:memory for me but when i hit "Minimize memory" my winxp has been totally crashed without blue screen. So it is dangerous feature for now.

Same, but with BSOD.
[bsv_minimizememory.txt](https://github.com/Feodor2/Mypal68/files/8445594/bsv_minimizememory.txt)

**Comment by win98se** [comment]
I'm not sure if the BSoD will happen everytime or occasionally, however I disabled `browser.tabs.remote.autostart` in `about:config`, and after browser restart, it works fine here.
![image](https://user-images.githubusercontent.com/11819816/162346083-6f1304ff-a30a-4bec-9531-97b235ed034b.png)

**Comment by MyTDT-Mysoft** [comment]
way to go using buggy features on buggy code and complaining on XP :P

**Comment by chrischris888** [comment]
I started to have blue screen incidents immediately after installing the portable version of MyPal 68. First it appeared after more then 4 tabs opened, then reducing to two and managing from the Toolbar Bookmark it was a little better, but however, when someone sent me a youtube link from the facebook chat messenger, I opened that  link in a separate tab and  immediately after closing the you tube video, the system crashed again into the blue screen. I am using XP SP3 MCE 2004 with 3,49 GB Ram "seen" from the 4GB of RAM installed, but however, unlike MyPal 29 ... this version is not supported well and it "demands" impossible amount of RAM, or else the windows must crash into the blue screen. I was very very happy at first to see it running on the net with great speed and for the first time  in the past 6 months I could use the Facebook Messenger again... because in the 29th version is no longer possible.

**Comment by chrischris888** [comment]
I forgot to mention that I am also using a manual "clear RAM memory" operation as often as I can, or just before closing MyPal68 I press the button "clear RM memory" and immediately after that I am closing much safely the MyPal68 ... but still could not avoid entirely NOT TO CRASH ANYMORE ... it still does and make Windows crash into the blue screen.

**Comment by Feodor2** [comment]
I looked the report why many things are empty.
It should looks like this
![image](https://user-images.githubusercontent.com/19492771/170549027-82039f05-91bf-4b1f-950a-7af80fc70156.png)

**Comment by pachuco** [comment]
I am not sure. Maybe I have to change BSOD dump settings?

**Comment by Feodor2** [comment]
Did you poked this settings? While i do not remember did i ever touch such settings.

**Comment by RickzDO** [comment]
> Just a complete crash with bluescreen, when I close mypal. ![Screenshot](https://user-images.githubusercontent.com/49531928/162186112-bdb00f73-64a7-408e-a069-42da5b021cf7.jpg)
> 
> I never had this error before.

same here!

**Comment by Feodor2** [comment]
Read carefully what data to provide while this screenshot is useless
