### ISSUE TITLE
Missing VMP signature on your browser.

### ISSUE THREAD

**Issue by Marietto2008** [Feodor2/Mypal68#430]
Hello.

I'm a regular subscriber of the service NowTV. I would like to see their content using Linux,but they don't allow this. They are forcing us to use Windows. That's not good. I tried to use your browser,but it didn't help. Can you mitigate the problem of the missing VMP signature on your browser ?

**Comment by Feodor2** [comment]
Did not get anything, never seen that service.
Elaborate anther way and give links may be too.
If this is about some closed source stuff like widewine, then I wont fix it ever.

**Comment by Marietto2008** [comment]
NowTV is the cheap SKY pay per view service. Very well known all over the world. I don't think that the problem is widevine. I'm asking all around.  Please give a look here :

https://github.com/win32ss/supermium/issues/497#issuecomment-2073287110

and you will understand what happens from one experienced developer.

**Comment by Feodor2** [comment]
May be you do not understand the meaning of 'proprietary' because you were already answered, there in supremium issue.
This browser is certainly not, moreover it does not support widevine at all and never will.

So this NowTV service dictates to use one OS and one browser I see you want dodge them, yes this is better then simple obey.
