### ISSUE TITLE
Chase bank login page

### ISSUE THREAD

**Issue by 85rx7se** [Feodor2/Mypal68#44]
Chase bank login page: https://secure07b.chase.com/web/auth/dashboard#/dashboard/index/index
does not like Mypal 68 .... comes up with a system requirements page (which says Firefox 76 or newer)
so we can not logon ... But Mypal 29.3.0 still works just fine, except that scripts run slowly and we
need to hit the error message when it comes up.  .... So it needs more tinkering to get 
everything just right. But issues like these are to be expected in a project like this.

**Comment by win98se** [comment]
Workaround: In `about:config`, create a new string value named `general.useragent.override.chase.com`, and set it to `Mozilla/5.0 (Windows NT 5.1; rv:100.0) Gecko/20100101 Firefox/100.0`.

FYI, Mypal 29.3.0 worked fine because it has the almost same workaround, except it spoofed as version 79 instead of 100.

**Comment by NEO-SPECTRUMAN** [comment]
and some sites already block this v79 as obsolete...

**Comment by win98se** [comment]
That is why I put version 100 instead of 79...
