### ISSUE TITLE
Mypal Port to PowerPC

### ISSUE THREAD

**Issue by Winman486** [Feodor2/Mypal68#46]
Will this ever be ported to PowerPC? Also is there a better way to get in touch with you than through the issues page?

**Comment by NEO-SPECTRUMAN** [comment]
ну тут маководы сами виноваты
они знали что покупают продукцию корпорации зла
и теперь (и всегда) должны страдать

**Comment by Feodor2** [comment]
Simple we do not use such stuff here ever, nobody wont have it at all.
And this is better way

**Comment by bludotbat** [comment]
i agree

**Comment by win98se** [comment]
@Winman486 You're probably better off using [TenFourFox](https://github.com/classilla/tenfourfox/wiki) instead if you're still using Mac OS X; AFAIK, latest Firefox versions are available for Debian for `ppc64el`, not sure if it applies to you.

**Comment by archipelagu** [comment]
@win98se
Suggesting Debian to an old Mac OS user is like suggesting a Windows 98/2000/XP/Vista user use Linux. It's certainly an option for some people, but usually people like their familiar old system (Mac/Win).

Fedor is right, Mac OS (especially older versions) is not popular here (but iPhone is popular). Partly because of the high price (although this doesn't prevent people from buying mobile devices, apparently they are bought by a different audience). Partly because computers in the ex-USSR came quite late. But definitely Mac OS (old/new) is an interesting OS.

**Comment by win98se** [comment]
The latter is clearly not a suggestion at all, and I gave priority to the first option.

**Comment by NEO-SPECTRUMAN** [comment]
>(but iPhone is popular

среди кого он популярный?
