### ISSUE TITLE
Opening new tab does not carry over referrer in 68.14.3

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#490]
For example when viewing Pixiv with the Mini Pixiv extension, images require the referrer header to load and not 403. Starting in 68.14.3, opening in new tab, whether it be by middle click, right click and open in new tab, or drag to the tab bar, none of the send the referrer header and result in a 403. The only thing that works is basic single clicking the image.

**Comment by Feodor2** [comment]
How I suppose to check this if already fixed?

**Comment by K4sum1** [comment]
It's a new issue? It appeared in 68.14.3.

**Comment by Feodor2** [comment]
So what, I wanted to check, okey next you do issues without details and do not elaborate, I just ignore then.

**Comment by K4sum1** [comment]
I don't know what else to add?

**Comment by Feodor2** [comment]
Links at least, may be other details about how to reproduce.

**Comment by K4sum1** [comment]
I'll make basic guide when back at computer

**Comment by zanud** [comment]
Below is a screenshot of Mepal console after two visiting of thre same link "[Плагины OpenSearch](http://yup.lh1.in/OpenSearch/index.html)" from http://yup.lh1.in/ homepage.
First visit was by Ctrl+click on link (in order to open it in a new tab).
Second visit was by regular click in link.
![referer](https://github.com/user-attachments/assets/1cb0917f-c8f3-48c8-b167-5525d25240fb)
As you see, only second request's header contains a "Referer" line.

You can easily reproduce this effect on any link and see the result in the console.

</span>
</body>
</html>"

**Comment by Feodor2** [comment]
Thanks zanud
It is "Referer" line on both things, consider this is fixed, new version will be soon.

**Comment by zanud** [comment]
BTW, above the first visit info the console contains an error message:
![referer2](https://github.com/user-attachments/assets/20450632-2931-49a3-8316-1d4a0631b3a6)

**Comment by Feodor2** [comment]
No message now.
