### ISSUE TITLE
XP FATAL ERROR and System Clash

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#56]
Since today, on Github, the Repository Number Field does no longer display the amount of Github Repositories in Numbers (momentarely 4'840), when touching the Number Field with the Mouse Marker. And if I use the system INSPECT ELEMENT Function, it results in a FATAL ERROR and the XP System crashes and resets/reboots. 
----
![xp_system_breakdown](https://user-images.githubusercontent.com/12776547/166113193-2607d055-e4b3-46f8-b849-0db06e1ccd85.png)

**Comment by Feodor2** [comment]
Did you mean this, how to reproduce the? Are you on the SP2?
![image](https://user-images.githubusercontent.com/19492771/166118072-829dea1d-4715-4173-849a-23e9aa1f2c0c.png)

**Comment by IP-CAM** [comment]
Negative, I use latest SP-3 XP Version. And it's exactly the link shown in your image, what makes my XP break down.

**Comment by Feodor2** [comment]
My be extensions, what about vanilla profile?

**Comment by IP-CAM** [comment]
this is what I get:
![error_info](https://user-images.githubusercontent.com/12776547/166122531-a54fd444-5fb9-491b-a598-a3bd369e51f6.png)

**Comment by IP-CAM** [comment]
![error_info2](https://user-images.githubusercontent.com/12776547/166138333-46eacca5-009e-4d59-be8f-db7537afbc67.png)

**Comment by Feodor2** [comment]
And what was the reason of the crash

**Comment by chrischris888** [comment]
@ Feodor2

Dear Feodor2

Please help me with these questions:

   1)  If I install ERAM or DATARAM on my Windows XP, in order to add 1 more GB of RAM, will this solve the blue screen issue after MyPal 68 crashes the windows ?
    2) Shall I wait for a new MyPal 68 upgraded version ?
    3) Does ERAM or DATARAM allow for using the extra ram for browser cache in order to avoid crashing into blue screen ?

**Comment by Feodor2** [comment]
@chrischris888 
1. Do not know what is ERAM or DATARAM and this certainly will not solve
2. Yes
3. Don't know at all  - never used such things.

Assume not get the blues screen with other software i think it happens because on particular drivers and can be any drivers to start with antivirus and such similar.

**Comment by chrischris888** [comment]
@Feodor2

Thank you very much for your great effort in solving this drivers problem. I am using Avast Antivirus for Windows XP for more then 11 years and is working very good.

**Comment by andika207** [comment]
@chrischris888 personally I don't run any real-time AV and the free ones's background process (like AVAST) cannot be disabled because it's sending your personal data back to their servers.

with regards to your question, NO additional RAM will prevent your machine from shutting down
I have a bunch of unused DDR2 (1GB, 2GB, 4GB) that could serve you well.
