### ISSUE TITLE
Windows Vista Aero border problem

### ISSUE THREAD

**Issue by InfinityTL** [Feodor2/Mypal68#58]
There are only three sides of the Aero effrct border under the window, and the above is not rendered by the Aero effect (I don't know if FireFox does it intentionally), but displays a style similar to Windows 10
![新建位图图像](https://user-images.githubusercontent.com/67815438/166180603-f29583ad-990b-44ba-88a2-dd5775072953.jpg)

**Comment by foxtrot-99** [comment]
In menu-cusomize, check title bar. It will partially fix it but the tab bar is still not glassed

**Comment by 1280px** [comment]
It probably happens because Firefox's CSS doesn't have support for Vista as is wasn't ever intended to be launched on it.

You'll need to tinker with CSS a little... What I think can be done is go to
https://github.com/Feodor2/Mypal68/blob/main/browser/themes/windows/browser.css
https://github.com/Feodor2/Mypal68/blob/main/browser/themes/windows/browser-aero.css
https://github.com/Feodor2/Mypal68/blob/main/browser/themes/windows/compacttheme.css
these files,

find Windows 7 @media in Mozilla's CSS files (sth like this: `@media (-moz-platform: windows-win7)` ) and add `windows-vista;` before so the thing will look sth like `@media (-moz-platform: windows-vista; windows-win7)`

**Comment by 1280px** [comment]
> find Windows 7 @media in Mozilla's CSS files (sth like this: `@media -moz-platform: windows-win7)` ) and add `windows-vista;` before so the thing will look sth like `@media (-moz-platform: windows-vista; windows-win7)`

nvm, I did a few experiments and I see the issue now. Mozilla deleted "windows-vista" and "windows-xp" media queries in FF57, so the method above won't work.

The solution I came up with is to use `-moz-windows-glass`, which is only triggered by Windows Vista and 7, when Aero Glass is enabled. Pay attention this method will *not* work if you're using Vista with Aero Basic theme (which still looks pretty good).

You can get modified CSS files here: 
https://github.com/1280px/Mypal68_AeroVista/commits/main

Also I made a pull request (tested on Windows XP, Windows Vista and Windows 7):
https://github.com/Feodor2/Mypal68/pull/63

**Comment by Feodor2** [comment]
I shall look into this after resolving major issues like crashes.

**Comment by win98se** [comment]
I suggest that this issue is to be closed because it is solved by #63. Thank you, @1280px!

![image](https://user-images.githubusercontent.com/11819816/188057039-237da287-3425-4e1b-bf3e-a307c14de3ec.png)
