### ISSUE TITLE
Mypal 68 - Portable

### ISSUE THREAD

**Issue by hmnogueira** [Feodor2/Mypal68#67]
I need a version o Mypal 68 fully portable.
When is used on a pendrive every thing is lost when used on a diferent computer.
how can i create a fully portable version.

Thanks to all

**Comment by NEO-SPECTRUMAN** [comment]
put pmprt.mod (blank file) to browser folder
https://github.com/Feodor2/Mypal/wiki/Portable#advanced-stuff

**Comment by hmnogueira** [comment]
[NEO-SPECTRUMAN](https://github.com/NEO-SPECTRUMAN) 
I have tried like you instructed, but every time de pendrive changes letter 
it opens a pink windows with a error
![mypal68 error](https://user-images.githubusercontent.com/105717446/168813318-3cd1ced7-06c2-467b-8dea-3c3797f32219.JPG)

**Comment by hmnogueira** [comment]
The problem is when i launch mypal it creates a profile folder on c: user profiles.
I dont want this. I want the profile folder to stay on the pendrive inside de mypal folder.

When the pendrive changes letter, all the plugins and other extras have to be reinstalled.

So i launch mypal with this instruction:
E:\mypal-68_portable\mypal.exe -no-remote -Profile Profile/
But when pendrive changes letter the blue screen error appears.

**Comment by NEO-SPECTRUMAN** [comment]
try to put pmprt.mod and launch without " -no-remote -Profile Profile/" arguments
https://github.com/Feodor2/Mypal/wiki/Portable#advanced-stuff

**Comment by hmnogueira** [comment]
Is pmprt.mod a normal text file?

**Comment by NEO-SPECTRUMAN** [comment]
is blank 0 bytes file

**Comment by NEO-SPECTRUMAN** [comment]
[pmprt.zip](https://github.com/Feodor2/Mypal68/files/8741911/pmprt.zip)

**Comment by hmnogueira** [comment]
I have done like you instructed, but when the drive letter changes it appeares the blue screen above. :(

**Comment by visionhelp** [comment]
If I may ask: what is the reason the drive letter (?) ALWAYS does change ? 
This can not be solved within the browser.

**Comment by Feodor2** [comment]
Do you want to say that drive letter itself accidentally changes?

**Comment by hmnogueira** [comment]
A use mypal on diferent computers, i dont use always the same computer. 
Sometimes the pendrive letter changes, because the computers are used by
others too.
I have found a solution but is not the ideal.
I created a shortcut with a diferent pendrive letter and it solve the problem.
The ideal is when i start mypal it find automaticaly the path of the profile on the pendrive.

**Comment by visionhelp** [comment]
[hmnogueira]. OK. Thanks. 
To me this profile folder on C: confuses me, now just first basically, because of this browser install is no install, just copy the folder to for example Programs, and make a link to the start-file, and put this link to desktop or on pendrive, or USB-stick. From this it appears already Portable, to be. 
But ´profile folder´ to C: speaks against it, from my understanding. 
Because, first: using pendrive (or USB-stick) on an other PC creates a profile folder there, too. 
Why not create this profile folder on the pendrive, would be my next question. 
Second: having a profile folder on an other PC I would like to avoid, too. 
If now for some times this browser will work this way: if there is anything from importance (in this profile-folder), for example all changed settings, it could be created a batch file to copy the file(s) from this folder to the pendrive and to delete these file(s) there, placed on the desktop or the pendrive. 
(I am curious.)

**Comment by visionhelp** [comment]
If this Profile folder in C: is perhaps to have the profile files ´just´ secure, not being (accidently) over-written by copying new version(s) ?

**Comment by hmnogueira** [comment]
I have put the pmprt.mod file on the browser folder on the pendrive and it works fine.
The profile is in the pendrive also.
As long as i don't change the pendrive letter, every thing works fine, settings, extras installed, bookmarks, etc.
All of this stay at the pendrive.

**Comment by visionhelp** [comment]
"**As long as i don't change the pendrive letter**": 
Could here be the origin of this problem: relative paths instead of direct (absolute) path ? 
As origin of the blue screen. 
Just an idea: Where being file(s) in use from Mypal86, one or more, with absolute path the change of the drive-letter could require a relative path to work.

**Comment by visionhelp** [comment]
Oh. Thanks. 
Making Mypal68 portable ´just´ needs to create the folder Profiles´ in the ´mypal´ folder and copy the files from the C: ... Profiles folder as shown by **about:profiles** ? 
Great, and happy: now I understand, wonderful. Just copy a new version folder ´Mypal´ to, over the existing folder, does not have on effect to the folder ´Profiles´.

**Comment by jasonliul** [comment]
wow, that's too simple, don't know should laugh or cry.

**Comment by visionhelp** [comment]
So, simple staying, please: It does not prevent an other PC being created (mypal´s) profiles-files, or and more ?

**Comment by visionhelp** [comment]
hmnogueira 
Did You find a solution ? 

"It changes before i start the browser.
Ex. I use the pendrive in a computer and it gives a letter to the pendrive, then i change computer and the new computer gives it a new drive letter to the pendrive.": 

Putting the pendrive to an other PC, this PC gives the pendrive an other drive-letter. 
There from, that this other PC has its own XP - Documents and Settings folder, for mypal-profile and so on -, there when starting mypal should be created a new own profiles there, if wanted or not. 
But which must not work, when this drive-letter the next time sticking in the pendrive into, when this drive-letter there is changed again. 
(What do I not understand correctly ?)
