### ISSUE TITLE
Mypal78

### ISSUE THREAD

**Issue by dainiusb** [Feodor2/Mypal68#95]
Firefox 68 is getting long in the tooth. It's my main browser on Win 10, but more and more websites no longer work with it. Same issues with Mypal of course. Perhaps it'd be better to let this one go and move to 70?

**Comment by NoNameNeeded2** [comment]
I don't really understand why but as far as I know Feodor plans to port Firefox 68, 78 and 91 to Windows XP and then he plans to support the version which works best.
I would personally go for Firefox 91 if that is possible (if I had the skills Feodor has) but it's still quite amazing that Firefox 68 (or Mypal68, to be precise) even runs on XP.
(Firefox 70 probably wouldn't make much difference in terms of web compatibility)

**Comment by dainiusb** [comment]
It does make a whole lot of difference for me, but I don't care if the next version is 70 or 78.

**Comment by Feodor2** [comment]
68 still not complete

**Comment by dainiusb** [comment]
Okay, but does it have to be complete? If it's outdated already.

**Comment by Feodor2** [comment]
So what, i make browser for winxp which became outdatet much long ago.
At least i want to resolve errors and finally to make languages and installer.

**Comment by dainiusb** [comment]
You do whatever you want, you're our only hope (besides 360 browser).

**Comment by AstroSkipper** [comment]
> You do whatever you want, you're our only hope (besides 360 browser).

Requesting further versions, discrediting existing version 68, and so on, is totally contraproductive and, truth be told, disrespectful. We have to be glad that there is a person willing to spend time to support an outdated, depreciated OS. Thinking about the future is ok in general, but first, completing the current version 68 is the goal. So my advice, be more respectful, help Feodor2 to finalize his project or do it on your own!

Regards, AstroSkipper

**Comment by sirrooster** [comment]
I <3 MyPal68. It's allready much better than the old MyPal based on Palemoon. In such a short time. GREAT :-)

**Comment by NoNameNeeded2** [comment]
I think everybody here really appreciates Feodor's work, no doubt in my mind.

But the question is, is it worth the effort to fix all the issues Mypal68 has when it's already quite outdated?
If he really plans to port versions 68, 78 and 91 then I would look at version 91 first, see what's possible and then go back one version if 91 can't be made to work to see if version 78 is better etc.

The argument that Windows XP is outdated isn't really a good one because that's the reason why we're all here: We are interested to see if a more recent browser can be made to run nicely on Windows XP even though it's outdated, which kind of "updates" the OS in a way. 
You could use tons of outdated browsers with Windows XP, but that's not the point.

But don't get me wrong:
I was amazed to see that Feodor was able to get version 68 to run on XP and I'm thankful that there now is a firefox-based browser much newer than 52 that XP-users can use.

**Comment by AstroSkipper** [comment]
> The argument that Windows XP is outdated isn't really a good one because that's the reason why we're all here.

I'm **absolutely not** in your opinion. I love Windows XP, and it's my main OS, but, truth has to be told, it is totally outdated and abandonded by Microsoft since 2014. Therefore, my argument is absolutely appropriate. Mypal 68 is a great step to get a more recent browser in Windows XP.  Are you the developer of this browser? Or a programmer working on this project? It is a project of Feodor2, and no one else. He decides what to do next or not. 

>It's about something that Feodor himself said: That he plans to port versions 68, 78 and 91.

Feodor2 stated to complete the project Mypal 68 first. Actually, there is nothing more to say. These issues should help him to finalize Mypal 68, and no other version. Any statements to stop this development, to change to a higher version, and so on is **defintely** disrespectful. If I were Feodor2, **I would be annoyed** by such comments. I quote Feodor2's comments for you and for all, demanding higher, mor recent versions:

> 68 still not complete

> So what, i make browser for winxp which became outdated much long ago.
At least i want to resolve errors and finally to make languages and installer.

Truth be told, there is nothing more to say. We should support Feodor2 to complete Mypal 68 first. **And it doesn't matter what others desire**. It's Feodor2's decision. 

Cheers, AstroSkipper [![ordi1fun.gif](https://i.postimg.cc/k4q8W73j/ordi1fun.gif)](https://postimg.cc/FfC745Kc)

**Comment by NoNameNeeded2** [comment]
The point is, you have tons of outdated browsers on XP. That's nothing special, that's just normal.

Of course it's Feodor's decision and as I said: No one **demands** a newer version of Mypal.
But if it is **his** **_plan_** to port more recent versions as well anyway, then why not move on to the next step now that it is clear that Firefox Quantum browsers can be made to run on XP (Mypal68 being a proof of concept)?
Why bother to fix issues which might not be there in more recent versions **OR** which require different solutions (therefore finding a solution for Mypal68 would be a waste of time for **him**, not for me or anyone else)?
These are fair questions to ask.

Unless he has changed his plans.
Maybe he now plans to port version 68 **only** and that's it.
That would be fine by me because it's his decision and Mypal68 is already better and more compatible than Mypal29 AND Palemoon.
But it would be something completely different.
That's not what I'm talking about here.

**Comment by NoNameNeeded2** [comment]
P.S. You seem to think that some of us here aren't grateful enough and are demanding more and more, not appreciating what Feodor has achieved.

But I think you're wrong about that. I can only speak for myself but all I can say is that I'm still amazed that even Firefox 68 (or Mypal68) works on XP.
Many people never thought that's even possible. Until Feodor just came along and did the unthinkable.
It's amazing and I think all of us here appreciate his efforts and are happy to help finding bugs.

But that's not the point here.

**Comment by AstroSkipper** [comment]
> No one **demands** a newer version of Mypal. But if it is **his** **_plan_** to port more recent versions , then **_why not move on to the next step now_** that it is clear that Firefox Quantum browsers can be made to run on XP (Mypal68 being a proof of concept)? **_Why bother to fix issues which might not be there in more recent versions_** **OR** which require different solutions (therefore finding a solution for Mypal68 would be a waste of time for **him**, not for me or anyone else)? These are fair questions to ask.

Thinking about the future of this project, is absolutely ok. But that's not what you are doing. I think the users here have two choices: to support completing Mypal 68 or not. What kind of user are you? Any statements to leave Mypal 68 and to go on with a higher version are **totally contraproductive**. And as I already said, you don't have to understand that. The completion of Mypal 68 is the goal and **nothing else**. Therefore, do not hinder Feodor2 in his work but help him to finalize Mypal 68! [![jaioublie.gif](https://i.postimg.cc/mrwhfMJw/jaioublie.gif)](https://postimg.cc/nsXnqsHj)

Cheers, AstroSkipper [![internet3.gif](https://i.postimg.cc/cJqf4QDG/internet3.gif)](https://postimg.cc/JsqspBVp)

**Comment by NoNameNeeded2** [comment]
> The completion of Mypal 68 is the goal and nothing else. 

But that's not what Feodor said.

And maybe you should calm down a little.
No one hinders Feodor to do whatever he plans to do.

**Comment by NoNameNeeded2** [comment]
Or let me put it differently:

If Feodor plans to stick with Mypal68 that would be just fine by me and I'd be happy to report bugs in order to fix those bugs.
But if he plans to port more recent versions as well, it wouldn't be necessary to fix every bug on Mypal68 or to create an installer and language packs (as you requested) since it would be a waste of time if Mypal68 isn't the final product.
It's not about being disrespectful.

Now it's up to Feodor which way he decides to go.

**Comment by NoNameNeeded2** [comment]
That's hard to answer.
Sometimes I'm able to read between the lines, I guess, most of the time actually.
Are you trying to tell me that Feodor tried to tell us between the lines that Mypal68 is going to be the final version?
Why wouldn't he just say it clearly? 
Makes no sense to me.
Or you mean something completely different, I don't know, I don't seem to be able to read between YOUR lines...;)

I'm the kind of user who is always interested when people get something to work on an OS that was never meant to be used on this OS and I'm also happy to help to find bugs in order to improve whatever it is.
Be it Mypal68 or Mypal91 or even Mypal169...;)

**Comment by AstroSkipper** [comment]
> Are you trying to tell me that Feodor tried to tell us between the lines that Mypal68 is going to be the final version?

No.

> I'm the kind of user who is always interested when people get something to work on an OS that was never meant to be used on this OS and I'm also happy to help to find bugs in order to improve whatever it is.
Be it Mypal68 or Mypal91 or even Mypal169...;)

That's what I wanted to hear. Very good! [![ssupercool2.gif](https://i.postimg.cc/zBP1TrbD/ssupercool2.gif)](https://postimg.cc/Hc5KCF9F) So let us help Fodor2 in completing **Mypal 68**, and all is well.

Cheers, AstroSkipper [![ecrire-ordi.gif](https://i.postimg.cc/g0mccjP2/ecrire-ordi.gif)](https://postimg.cc/1871J9tk)

**Comment by Feodor2** [comment]
I want complete 68 because it may be better than 91 or 78 so then i shall choose to stay with 68 ans its missed a little new features i shall add.

**Comment by SaranSDS008** [comment]
> Okay, but does it have to be complete? If it's outdated already.

I use Firefox Quantum 60 ESR (I prefer it, cuz i like it) as an alt browser in my main pc. Most of the sites work (few are broken though) if you bypass individual sites' UAC in about:config.

![image](https://user-images.githubusercontent.com/88842885/179393148-9783971c-d6a3-46c7-ba96-1ffb60908e88.png)
